export type ThemeMode = 'system' | 'light' | 'dark';
export type ResolvedTheme = Exclude<ThemeMode, 'system'>;
export type LocaleCode =
  'zh-CN' | 'en-US' | 'hi-IN' | 'es-ES' | 'ar-SA' | 'fr-FR' | 'bn-BD' | 'pt-BR' | 'ru-RU' | 'ja-JP';

export const LOCALES: ReadonlyArray<{ code: LocaleCode; label: string; dir: 'ltr' | 'rtl' }> = [
  { code: 'zh-CN', label: '简体中文', dir: 'ltr' },
  { code: 'en-US', label: 'English', dir: 'ltr' },
  { code: 'hi-IN', label: 'हिन्दी', dir: 'ltr' },
  { code: 'es-ES', label: 'Español', dir: 'ltr' },
  { code: 'ar-SA', label: 'العربية', dir: 'rtl' },
  { code: 'fr-FR', label: 'Français', dir: 'ltr' },
  { code: 'bn-BD', label: 'বাংলা', dir: 'ltr' },
  { code: 'pt-BR', label: 'Português', dir: 'ltr' },
  { code: 'ru-RU', label: 'Русский', dir: 'ltr' },
  { code: 'ja-JP', label: '日本語', dir: 'ltr' },
];

const KEYS = [
  'commandRoom',
  'waitingInput',
  'resultReady',
  'callFailed',
  'running',
  'online',
  'newRehearsal',
  'theme',
  'system',
  'light',
  'dark',
  'language',
  'experts',
  'currentSop',
  'recommendedSteps',
  'decisionNodes',
  'schemaPassed',
  'changedTopology',
  'waitingDecision',
  'consensus',
  'risk',
  'evidence',
  'waitingAnalysis',
  'resultPanel',
  'inputHeading',
  'title',
  'content',
  'start',
  'emptyBody',
  'failedTitle',
  'retry',
  'loadingTitle',
  'loadingText',
  'resultTitle',
  'disagreements',
  'decisions',
  'orbit',
  'reset',
] as const;
export type MessageKey = (typeof KEYS)[number];
export type Messages = Record<MessageKey, string>;

function pack(values: readonly string[]): Messages {
  return Object.fromEntries(KEYS.map((key, index) => [key, values[index]])) as Messages;
}

const PACKS: Record<LocaleCode, Messages> = {
  'zh-CN': pack([
    '议会指挥室',
    '等待 SOP 输入',
    '议会结果已生成',
    'A2MCP 调用失败',
    '三专家正在审议',
    'A2MCP 在线',
    '新建演练',
    '主题',
    '跟随系统',
    '浅色',
    '深色',
    '语言',
    '专家席位',
    '当前 SOP',
    '个推荐步骤',
    '个决策节点',
    'Schema 已通过',
    '决策已改变风险拓扑',
    '共识已建立 · 等待用户决策',
    '共识',
    '风险',
    '证据',
    '等待 A2MCP 分析',
    '议会结果',
    '输入待演练 SOP',
    '演练标题',
    'SOP 正文',
    '启动议会演练',
    '输入一段真实 SOP，三位 AI 专家将分别检查流程、风险与证据。',
    '本次审议未完成',
    '请确认服务在线，点击“新建演练”后重试。',
    '议会正在审议',
    '正在等待三位专家完成分析…',
    '议会结论',
    '分歧与证据缺口',
    '决策演练',
    '按住鼠标中键拖动 · 360° 环视',
    '复位视角',
  ]),
  'en-US': pack([
    'Council Command Room',
    'Waiting for SOP input',
    'Council result ready',
    'A2MCP call failed',
    'Three experts deliberating',
    'A2MCP online',
    'New rehearsal',
    'Theme',
    'System',
    'Light',
    'Dark',
    'Language',
    'Expert seats',
    'Current SOP',
    'recommended steps',
    'decision nodes',
    'Schema valid',
    'Decision changed the risk topology',
    'Consensus ready · awaiting your decision',
    'Consensus',
    'Risk',
    'Evidence',
    'Waiting for A2MCP analysis',
    'Council result',
    'Submit an SOP',
    'Rehearsal title',
    'SOP content',
    'Start council rehearsal',
    'Submit a real SOP. Three AI experts will inspect its process, risks and evidence.',
    'Deliberation incomplete',
    'Check that the service is online, then choose “New rehearsal” to retry.',
    'Council deliberating',
    'Waiting for all three experts…',
    'Council conclusions',
    'Disagreements & evidence gaps',
    'Decision rehearsal',
    'Hold middle mouse and drag · 360° orbit',
    'Reset view',
  ]),
  'hi-IN': pack([
    'परिषद नियंत्रण कक्ष',
    'SOP इनपुट की प्रतीक्षा',
    'परिषद परिणाम तैयार',
    'A2MCP कॉल विफल',
    'तीन विशेषज्ञ विचार कर रहे हैं',
    'A2MCP ऑनलाइन',
    'नया अभ्यास',
    'थीम',
    'सिस्टम',
    'हल्का',
    'गहरा',
    'भाषा',
    'विशेषज्ञ सीटें',
    'वर्तमान SOP',
    'अनुशंसित चरण',
    'निर्णय नोड',
    'स्कीमा मान्य',
    'निर्णय ने जोखिम मानचित्र बदला',
    'सहमति तैयार · निर्णय की प्रतीक्षा',
    'सहमति',
    'जोखिम',
    'साक्ष्य',
    'A2MCP विश्लेषण की प्रतीक्षा',
    'परिषद परिणाम',
    'अभ्यास हेतु SOP दें',
    'अभ्यास शीर्षक',
    'SOP सामग्री',
    'परिषद अभ्यास शुरू करें',
    'वास्तविक SOP दें। तीन AI विशेषज्ञ प्रक्रिया, जोखिम और साक्ष्य जाँचेंगे।',
    'विचार-विमर्श अधूरा',
    'सेवा ऑनलाइन जाँचें और “नया अभ्यास” चुनकर पुनः प्रयास करें।',
    'परिषद विचार कर रही है',
    'तीनों विशेषज्ञों की प्रतीक्षा…',
    'परिषद निष्कर्ष',
    'मतभेद व साक्ष्य अंतर',
    'निर्णय अभ्यास',
    'मध्य माउस दबाकर खींचें · 360° दृश्य',
    'दृश्य रीसेट',
  ]),
  'es-ES': pack([
    'Sala de mando del consejo',
    'Esperando un SOP',
    'Resultado listo',
    'Falló la llamada A2MCP',
    'Tres expertos deliberando',
    'A2MCP en línea',
    'Nuevo ensayo',
    'Tema',
    'Sistema',
    'Claro',
    'Oscuro',
    'Idioma',
    'Puestos expertos',
    'SOP actual',
    'pasos recomendados',
    'nodos de decisión',
    'Esquema válido',
    'La decisión cambió el mapa de riesgo',
    'Consenso listo · esperando decisión',
    'Consenso',
    'Riesgo',
    'Evidencia',
    'Esperando análisis A2MCP',
    'Resultado del consejo',
    'Enviar un SOP',
    'Título del ensayo',
    'Contenido del SOP',
    'Iniciar ensayo',
    'Envía un SOP real. Tres expertos de IA revisarán proceso, riesgos y evidencia.',
    'Deliberación incompleta',
    'Comprueba el servicio y usa “Nuevo ensayo” para reintentar.',
    'Consejo deliberando',
    'Esperando a los tres expertos…',
    'Conclusiones',
    'Desacuerdos y brechas',
    'Ensayo de decisión',
    'Mantén el botón central y arrastra · vista 360°',
    'Restablecer vista',
  ]),
  'ar-SA': pack([
    'غرفة قيادة المجلس',
    'بانتظار إدخال SOP',
    'نتيجة المجلس جاهزة',
    'فشل اتصال A2MCP',
    'ثلاثة خبراء يتداولون',
    'A2MCP متصل',
    'تمرين جديد',
    'المظهر',
    'النظام',
    'فاتح',
    'داكن',
    'اللغة',
    'مقاعد الخبراء',
    'SOP الحالي',
    'خطوات موصى بها',
    'عقد القرار',
    'المخطط صالح',
    'القرار غيّر خريطة المخاطر',
    'الإجماع جاهز · بانتظار قرارك',
    'الإجماع',
    'المخاطر',
    'الأدلة',
    'بانتظار تحليل A2MCP',
    'نتيجة المجلس',
    'أدخل SOP للتمرين',
    'عنوان التمرين',
    'محتوى SOP',
    'ابدأ تمرين المجلس',
    'أدخل SOP حقيقياً. سيفحص ثلاثة خبراء ذكاء اصطناعي العملية والمخاطر والأدلة.',
    'المداولة لم تكتمل',
    'تحقق من اتصال الخدمة ثم اختر «تمرين جديد» للمحاولة.',
    'المجلس يتداول',
    'بانتظار الخبراء الثلاثة…',
    'استنتاجات المجلس',
    'الخلافات وفجوات الأدلة',
    'تمرين القرار',
    'اضغط زر الفأرة الأوسط واسحب · عرض 360°',
    'إعادة العرض',
  ]),
  'fr-FR': pack([
    'Salle de commandement',
    'En attente du SOP',
    'Résultat du conseil prêt',
    'Échec de l’appel A2MCP',
    'Trois experts délibèrent',
    'A2MCP en ligne',
    'Nouvelle simulation',
    'Thème',
    'Système',
    'Clair',
    'Sombre',
    'Langue',
    'Sièges experts',
    'SOP actuel',
    'étapes recommandées',
    'nœuds de décision',
    'Schéma valide',
    'La décision a modifié la topologie du risque',
    'Consensus prêt · décision attendue',
    'Consensus',
    'Risque',
    'Preuves',
    'En attente de l’analyse A2MCP',
    'Résultat du conseil',
    'Soumettre un SOP',
    'Titre de la simulation',
    'Contenu du SOP',
    'Lancer la simulation',
    'Soumettez un vrai SOP. Trois experts IA examineront processus, risques et preuves.',
    'Délibération incomplète',
    'Vérifiez le service puis choisissez « Nouvelle simulation » pour réessayer.',
    'Conseil en délibération',
    'En attente des trois experts…',
    'Conclusions',
    'Désaccords et preuves manquantes',
    'Simulation de décision',
    'Maintenez le bouton central et glissez · vue 360°',
    'Réinitialiser',
  ]),
  'bn-BD': pack([
    'কাউন্সিল কমান্ড রুম',
    'SOP ইনপুটের অপেক্ষা',
    'কাউন্সিল ফল প্রস্তুত',
    'A2MCP কল ব্যর্থ',
    'তিন বিশেষজ্ঞ আলোচনা করছেন',
    'A2MCP অনলাইন',
    'নতুন অনুশীলন',
    'থিম',
    'সিস্টেম',
    'হালকা',
    'গাঢ়',
    'ভাষা',
    'বিশেষজ্ঞ আসন',
    'বর্তমান SOP',
    'প্রস্তাবিত ধাপ',
    'সিদ্ধান্ত নোড',
    'স্কিমা বৈধ',
    'সিদ্ধান্ত ঝুঁকি মানচিত্র বদলেছে',
    'ঐকমত্য প্রস্তুত · সিদ্ধান্তের অপেক্ষা',
    'ঐকমত্য',
    'ঝুঁকি',
    'প্রমাণ',
    'A2MCP বিশ্লেষণের অপেক্ষা',
    'কাউন্সিল ফল',
    'অনুশীলনের SOP দিন',
    'অনুশীলনের শিরোনাম',
    'SOP বিষয়বস্তু',
    'কাউন্সিল অনুশীলন শুরু',
    'একটি বাস্তব SOP দিন। তিন AI বিশেষজ্ঞ প্রক্রিয়া, ঝুঁকি ও প্রমাণ যাচাই করবে।',
    'আলোচনা অসম্পূর্ণ',
    'সেবা অনলাইন কিনা দেখে “নতুন অনুশীলন” দিয়ে আবার চেষ্টা করুন।',
    'কাউন্সিল আলোচনা করছে',
    'তিন বিশেষজ্ঞের অপেক্ষা…',
    'কাউন্সিল সিদ্ধান্ত',
    'মতভেদ ও প্রমাণ ঘাটতি',
    'সিদ্ধান্ত অনুশীলন',
    'মাঝের মাউস ধরে টানুন · 360° দৃশ্য',
    'দৃশ্য রিসেট',
  ]),
  'pt-BR': pack([
    'Sala de comando do conselho',
    'Aguardando SOP',
    'Resultado pronto',
    'Falha na chamada A2MCP',
    'Três especialistas deliberando',
    'A2MCP online',
    'Novo ensaio',
    'Tema',
    'Sistema',
    'Claro',
    'Escuro',
    'Idioma',
    'Assentos especialistas',
    'SOP atual',
    'etapas recomendadas',
    'nós de decisão',
    'Schema válido',
    'A decisão alterou o mapa de risco',
    'Consenso pronto · aguardando decisão',
    'Consenso',
    'Risco',
    'Evidência',
    'Aguardando análise A2MCP',
    'Resultado do conselho',
    'Enviar um SOP',
    'Título do ensaio',
    'Conteúdo do SOP',
    'Iniciar ensaio',
    'Envie um SOP real. Três especialistas de IA revisarão processo, riscos e evidências.',
    'Deliberação incompleta',
    'Verifique o serviço e escolha “Novo ensaio” para tentar novamente.',
    'Conselho deliberando',
    'Aguardando os três especialistas…',
    'Conclusões',
    'Divergências e lacunas',
    'Ensaio de decisão',
    'Segure o botão do meio e arraste · visão 360°',
    'Redefinir visão',
  ]),
  'ru-RU': pack([
    'Командный зал совета',
    'Ожидание SOP',
    'Результат совета готов',
    'Ошибка вызова A2MCP',
    'Три эксперта обсуждают',
    'A2MCP в сети',
    'Новая тренировка',
    'Тема',
    'Системная',
    'Светлая',
    'Тёмная',
    'Язык',
    'Места экспертов',
    'Текущий SOP',
    'рекомендованных шагов',
    'узлов решения',
    'Схема валидна',
    'Решение изменило карту рисков',
    'Консенсус готов · ждём решения',
    'Консенсус',
    'Риск',
    'Доказательства',
    'Ожидание анализа A2MCP',
    'Результат совета',
    'Отправить SOP',
    'Название тренировки',
    'Содержание SOP',
    'Начать тренировку',
    'Отправьте реальный SOP. Три ИИ-эксперта проверят процесс, риски и доказательства.',
    'Обсуждение не завершено',
    'Проверьте сервис и выберите «Новая тренировка».',
    'Совет обсуждает',
    'Ожидание трёх экспертов…',
    'Выводы совета',
    'Разногласия и пробелы',
    'Тренировка решения',
    'Удерживайте среднюю кнопку и тяните · обзор 360°',
    'Сбросить вид',
  ]),
  'ja-JP': pack([
    '評議会コマンドルーム',
    'SOP 入力待ち',
    '評議結果が完成',
    'A2MCP 呼び出し失敗',
    '3 名の専門家が審議中',
    'A2MCP オンライン',
    '新しい演習',
    'テーマ',
    'システム',
    'ライト',
    'ダーク',
    '言語',
    '専門家席',
    '現在の SOP',
    '推奨ステップ',
    '意思決定ノード',
    'スキーマ検証済み',
    '意思決定でリスク構造が変化',
    '合意形成済み · 判断待ち',
    '合意',
    'リスク',
    '証拠',
    'A2MCP 分析待ち',
    '評議結果',
    '演習する SOP を入力',
    '演習タイトル',
    'SOP 本文',
    '評議演習を開始',
    '実際の SOP を入力してください。3 名の AI 専門家が手順、リスク、証拠を確認します。',
    '審議を完了できませんでした',
    'サービスを確認し「新しい演習」から再試行してください。',
    '評議会が審議中',
    '3 名の専門家を待っています…',
    '評議会の結論',
    '相違点と証拠不足',
    '意思決定演習',
    'マウス中ボタンを押してドラッグ · 360° 回転',
    '視点を戻す',
  ]),
};

const EXTRA_KEYS = [
  'navHistory',
  'navEvidence',
  'navProtocol',
  'navSecurity',
  'procedureSeat',
  'riskSeat',
  'evidenceSeat',
  'disagreementPaths',
  'evidenceItems',
  'gaps',
  'consensusCore',
  'riskActivated',
  'safePath',
  'consensusStrength',
  'currentRisk',
  'evidenceCoverage',
  'riskLow',
  'riskMedium',
  'riskHigh',
  'byteUnit',
] as const;
export type ExtraMessageKey = (typeof EXTRA_KEYS)[number];
export type AppMessages = Messages & Record<ExtraMessageKey, string>;
function extra(values: readonly string[]): Record<ExtraMessageKey, string> {
  return Object.fromEntries(EXTRA_KEYS.map((key, index) => [key, values[index]])) as Record<
    ExtraMessageKey,
    string
  >;
}
const EXTRAS: Record<LocaleCode, Record<ExtraMessageKey, string>> = {
  'zh-CN': extra([
    '演练记录',
    '证据档案',
    '协议接口',
    '安全与权限',
    '流程席位',
    '风险席位',
    '证据席位',
    '条分歧路径',
    '项证据',
    '项缺口',
    '中央共识核心',
    '风险链路激活',
    '安全处置路径',
    '共识强度',
    '当前风险',
    '证据覆盖',
    '低',
    '中',
    '高',
    '字节',
  ]),
  'en-US': extra([
    'Rehearsal history',
    'Evidence archive',
    'Protocol API',
    'Security & access',
    'Procedure seat',
    'Risk seat',
    'Evidence seat',
    'disagreement paths',
    'evidence items',
    'gaps',
    'Central consensus core',
    'Risk path active',
    'Safe response path',
    'Consensus strength',
    'Current risk',
    'Evidence coverage',
    'Low',
    'Medium',
    'High',
    'bytes',
  ]),
  'hi-IN': extra([
    'अभ्यास इतिहास',
    'साक्ष्य संग्रह',
    'प्रोटोकॉल API',
    'सुरक्षा व पहुँच',
    'प्रक्रिया सीट',
    'जोखिम सीट',
    'साक्ष्य सीट',
    'मतभेद पथ',
    'साक्ष्य मद',
    'अंतर',
    'केंद्रीय सहमति',
    'जोखिम पथ सक्रिय',
    'सुरक्षित प्रतिक्रिया',
    'सहमति शक्ति',
    'वर्तमान जोखिम',
    'साक्ष्य कवरेज',
    'कम',
    'मध्यम',
    'उच्च',
    'बाइट',
  ]),
  'es-ES': extra([
    'Historial',
    'Archivo de evidencia',
    'API de protocolo',
    'Seguridad y acceso',
    'Puesto de proceso',
    'Puesto de riesgo',
    'Puesto de evidencia',
    'rutas de desacuerdo',
    'evidencias',
    'brechas',
    'Núcleo de consenso',
    'Ruta de riesgo activa',
    'Ruta de respuesta segura',
    'Fuerza del consenso',
    'Riesgo actual',
    'Cobertura de evidencia',
    'Bajo',
    'Medio',
    'Alto',
    'bytes',
  ]),
  'ar-SA': extra([
    'سجل التمارين',
    'أرشيف الأدلة',
    'واجهة البروتوكول',
    'الأمان والوصول',
    'مقعد الإجراءات',
    'مقعد المخاطر',
    'مقعد الأدلة',
    'مسارات خلاف',
    'عناصر أدلة',
    'فجوات',
    'نواة الإجماع',
    'مسار الخطر نشط',
    'مسار استجابة آمن',
    'قوة الإجماع',
    'الخطر الحالي',
    'تغطية الأدلة',
    'منخفض',
    'متوسط',
    'مرتفع',
    'بايت',
  ]),
  'fr-FR': extra([
    'Historique',
    'Archives de preuves',
    'API protocole',
    'Sécurité et accès',
    'Siège procédure',
    'Siège risque',
    'Siège preuves',
    'chemins de désaccord',
    'preuves',
    'lacunes',
    'Noyau du consensus',
    'Chemin de risque actif',
    'Réponse sûre',
    'Force du consensus',
    'Risque actuel',
    'Couverture des preuves',
    'Faible',
    'Moyen',
    'Élevé',
    'octets',
  ]),
  'bn-BD': extra([
    'অনুশীলন ইতিহাস',
    'প্রমাণ আর্কাইভ',
    'প্রোটোকল API',
    'নিরাপত্তা ও প্রবেশ',
    'প্রক্রিয়া আসন',
    'ঝুঁকি আসন',
    'প্রমাণ আসন',
    'মতভেদ পথ',
    'প্রমাণ উপাদান',
    'ঘাটতি',
    'কেন্দ্রীয় ঐকমত্য',
    'ঝুঁকি পথ সক্রিয়',
    'নিরাপদ প্রতিক্রিয়া',
    'ঐকমত্য শক্তি',
    'বর্তমান ঝুঁকি',
    'প্রমাণ কভারেজ',
    'কম',
    'মাঝারি',
    'উচ্চ',
    'বাইট',
  ]),
  'pt-BR': extra([
    'Histórico',
    'Arquivo de evidências',
    'API de protocolo',
    'Segurança e acesso',
    'Assento de processo',
    'Assento de risco',
    'Assento de evidência',
    'rotas de divergência',
    'evidências',
    'lacunas',
    'Núcleo de consenso',
    'Rota de risco ativa',
    'Resposta segura',
    'Força do consenso',
    'Risco atual',
    'Cobertura de evidências',
    'Baixo',
    'Médio',
    'Alto',
    'bytes',
  ]),
  'ru-RU': extra([
    'История тренировок',
    'Архив доказательств',
    'API протокола',
    'Безопасность и доступ',
    'Место процесса',
    'Место риска',
    'Место доказательств',
    'путей разногласий',
    'доказательств',
    'пробелов',
    'Ядро консенсуса',
    'Риск активирован',
    'Безопасный путь',
    'Сила консенсуса',
    'Текущий риск',
    'Покрытие доказательств',
    'Низкий',
    'Средний',
    'Высокий',
    'байт',
  ]),
  'ja-JP': extra([
    '演習履歴',
    '証拠アーカイブ',
    'プロトコル API',
    'セキュリティと権限',
    '手順席',
    'リスク席',
    '証拠席',
    '相違経路',
    '証拠項目',
    '不足',
    '中央合意コア',
    'リスク経路が作動',
    '安全対応経路',
    '合意強度',
    '現在のリスク',
    '証拠カバレッジ',
    '低',
    '中',
    '高',
    'バイト',
  ]),
};

export function getMessages(locale: LocaleCode): AppMessages {
  return { ...PACKS[locale], ...EXTRAS[locale] };
}

export function resolveTheme(mode: ThemeMode, prefersDark: boolean): ResolvedTheme {
  return mode === 'system' ? (prefersDark ? 'dark' : 'light') : mode;
}

export function getInitialLocale(language = navigator.language): LocaleCode {
  const exact = LOCALES.find(({ code }) => code.toLowerCase() === language.toLowerCase());
  if (exact) return exact.code;
  const base = language.split('-')[0];
  return LOCALES.find(({ code }) => code.startsWith(`${base}-`))?.code ?? 'en-US';
}
